name: flutter_toast_pro
description: "Overlay-based toast/loading/progress helper for Flutter apps."
version: 1.1.1
homepage: https://github.com/Matkurban/flutter_toast_pro
repository: https://github.com/Matkurban/flutter_toast_pro
topics: [toast,message,loading,progress]

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.28.0
  rxdart_flutter: ^0.0.2
  loading_indicator: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
